### PR TITLE
Sphinx Maven proxy settings

### PR DESCRIPTION
**Pull request by donatelloOo**
fix for HTTPS support / allow more TLS protocols

### CODE REVIEW

**Comment by trustin** [comment]
Thanks! I cherry-picked your first commit into 6a501d123e90bdf5aaffad287fd117a345fbc1e0. I couldn't pull the second one in because it fails the CI build. Let me try to pull it in later.

**Comment by trustin** [comment]
@donatelloOo Could you try the master branch again and let me know if the problem is fixed?

**Comment by trustin** [comment]
Pushed a merge commit

**Comment by donatelloOo** [comment]
Worked good for me !
Now waiting next release to update our project plugin dependency.
Thanks.

**Pull request closed without merging**
